CREATE TABLE ACC_KEYS
(
	[id] INT IDENTITY(1,1) NOT NULL,
	[user_id] INT NOT NULL,
	[key] NVARCHAR(40) NOT NULL,
	[level] INT NOT NULL,
	[ignore_limits] TINYINT NOT NULL DEFAULT 0,
	[is_private_key] TINYINT NOT NULL DEFAULT 0,
	[ip_addresses] NVARCHAR(20) NULL DEFAULT NULL,
	[date_created] INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES ACC_PENGGUNA(ID_PENGGUNA) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE REF_STATUS_REFUND;
CREATE TABLE REF_STATUS_REFUND_OLD
(
	[ID_STATUS_REFUND] INT IDENTITY(1,1) NOT NULL,
	[STATUS_REFUND] NVARCHAR(255) NOT NULL,
	CONSTRAINT [PK_REF_STATUS_REFUND] PRIMARY KEY CLUSTERED
	([ID_STATUS_REFUND] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE REF_STATUS_REFUND
(
	[ID_STATUS_REFUND] INT IDENTITY(1,1) NOT NULL,
	[STATUS_REFUND] NVARCHAR(255) NOT NULL,
	PRIMARY KEY NONCLUSTERED (ID_STATUS_REFUND)
) WITH (MEMORY_OPTIMIZED=ON);

INSERT INTO REF_STATUS_REFUND(STATUS_REFUND) VALUES('DIAJUKAN');
INSERT INTO REF_STATUS_REFUND(STATUS_REFUND) VALUES('DIPROSES');

DROP TABLE TRX_TIKET_SALES_REFUND;
CREATE TABLE TRX_TIKET_SALES_REFUND_OLD
(
	[ID_TRX_TIKET_SALES_REFUND] INT IDENTITY(1,1) NOT NULL,
	[ID_TRX_TIKET_SALES] INT,
	[ID_STATUS_PESAN] INT,
	[ID_PENGGUNA] INT,
	[TGL_PENGAJUAN] DATE,
	[WAKTU_PENGAJUAN] TIME,
	[NAMA_PEMOHON] NVARCHAR(255),
	[ID_JENIS_IDENTITAS] INT,
	[NOMOR_IDENTITAS] NVARCHAR(255),
	[NOMOR_TELP] NVARCHAR(255),
	[ID_BANK] INT,
	[REKENING] NVARCHAR(255),
	[ATAS_NAMA] NVARCHAR(255),
	[ID_STATUS_REFUND] INT,
	[TGL_PROSES] DATE,
	[WAKTU_PROSES] TIME,
	[ALASAN] NVARCHAR(255),
	[TOTAL] INT DEFAULT 0,
	[REFUND] INT DEFAULT 0,
	CONSTRAINT [PK_TRX_TIKET_SALES_REFUND] PRIMARY KEY CLUSTERED 
	([ID_TRX_TIKET_SALES_REFUND] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE TRX_TIKET_SALES_REFUND
(
	[ID_TRX_TIKET_SALES_REFUND] INT IDENTITY(1,1) NOT NULL,
	[ID_TRX_TIKET_SALES] INT,
	[ID_STATUS_PESAN] INT,
	[ID_PENGGUNA] INT,
	[TGL_PENGAJUAN] DATE,
	[WAKTU_PENGAJUAN] TIME,
	[NAMA_PEMOHON] NVARCHAR(255),
	[ID_JENIS_IDENTITAS] INT,
	[NOMOR_IDENTITAS] NVARCHAR(255),
	[NOMOR_TELP] NVARCHAR(255),
	[ID_BANK] INT,
	[REKENING] NVARCHAR(255),
	[ATAS_NAMA] NVARCHAR(255),
	[ID_STATUS_REFUND] INT,
	[TGL_PROSES] DATE,
	[WAKTU_PROSES] TIME,
	[ALASAN] NVARCHAR(255),
	[TOTAL] INT DEFAULT 0,
	[REFUND] INT DEFAULT 0,
	PRIMARY KEY NONCLUSTERED (ID_TRX_TIKET_SALES_REFUND)
) WITH (MEMORY_OPTIMIZED=ON);

ALTER TABLE TRX_TIKET_SALES_REFUND ADD CONSTRAINT FK_TIKET_SALES_REFUND FOREIGN KEY(ID_TRX_TIKET_SALES) REFERENCES TRX_TIKET_SALES(ID_TRX_TIKET_SALES);
ALTER TABLE TRX_TIKET_SALES_REFUND ADD CONSTRAINT FK_STATUS_PESAN FOREIGN KEY(ID_STATUS_PESAN) REFERENCES REF_STATUS_PESAN(ID_STATUS_PESAN);
ALTER TABLE TRX_TIKET_SALES_REFUND ADD CONSTRAINT FK_PENGGUNA FOREIGN KEY(ID_PENGGUNA) REFERENCES ACC_PENGGUNA(ID_PENGGUNA);
ALTER TABLE TRX_TIKET_SALES_REFUND ADD CONSTRAINT FK_JENIS_IDENTITAS FOREIGN KEY(ID_JENIS_IDENTITAS) REFERENCES REF_JENIS_IDENTITAS(ID_JENIS_IDENTITAS);
ALTER TABLE TRX_TIKET_SALES_REFUND ADD CONSTRAINT FK_STATUS_REFUND FOREIGN KEY(ID_STATUS_REFUND) REFERENCES REF_STATUS_REFUND(ID_STATUS_REFUND);
	
CREATE INDEX TIKET_REFUND_TGL_PENGAJUAN ON TRX_TIKET_SALES_REFUND(TGL_PENGAJUAN);
CREATE INDEX TIKET_REFUND_TGL_PROSES ON TRX_TIKET_SALES_REFUND(TGL_PROSES);

INSERT INTO REF_BANK (KODE_BANK, NAMA_BANK) VALUES ('MDR', 'BANK MANDIRI');
INSERT INTO REF_BANK (KODE_BANK, NAMA_BANK) VALUES ('BNI', 'BANK BNI');
INSERT INTO REF_BANK (KODE_BANK, NAMA_BANK) VALUES ('BRI', 'BANK BRI');

-- DROP TABLE REF_ALASAN_REFUND;
CREATE TABLE REF_ALASAN_REFUND
(
	[ID_ALASAN_REFUND] INT IDENTITY(1,1) NOT NULL,
	[ALASAN] NVARCHAR(255) NOT NULL,
	[KETERANGAN] NVARCHAR(255),
	PRIMARY KEY NONCLUSTERED (ID_ALASAN_REFUND)
) WITH (MEMORY_OPTIMIZED=ON);

INSERT INTO REF_ALASAN_REFUND (ALASAN, KETERANGAN) VALUES ('DIBATALKAN', 'Dibatalkan Oleh Penyedia Jasa');
INSERT INTO REF_ALASAN_REFUND (ALASAN, KETERANGAN) VALUES ('RESCHEDULE', 'Reschedule Oleh Penyedia Jasa');
INSERT INTO REF_ALASAN_REFUND (ALASAN, KETERANGAN) VALUES ('DOUBLE BOOKING', 'Penyebrangan Yang Sama Dipesan Dua Kali');
INSERT INTO REF_ALASAN_REFUND (ALASAN, KETERANGAN) VALUES ('PRIBADI', 'Keinginan Penumpang');

-- DROP TABLE TRX_TIKET_REFUND;
CREATE TABLE TRX_TIKET_REFUND
(
	[ID_TRX_TIKET_REFUND] INT IDENTITY(1,1) NOT NULL,
	[ID_TRX_TIKET_SALES] INT,
	[ID_STATUS_PESAN] INT,
	[ID_PENGGUNA] INT,
	[TGL_PENGAJUAN] DATE,
	[WAKTU_PENGAJUAN] TIME,
	[NAMA_PEMOHON] NVARCHAR(255),
	[ID_JENIS_IDENTITAS] INT,
	[NOMOR_IDENTITAS] NVARCHAR(255),
	[NOMOR_TELP] NVARCHAR(255),
	[ID_BANK] INT,
	[REKENING] NVARCHAR(255),
	[ATAS_NAMA] NVARCHAR(255),
	[ID_STATUS_REFUND] INT,
	[TGL_PROSES] DATE,
	[WAKTU_PROSES] TIME,
	[ALASAN] NVARCHAR(255),
	PRIMARY KEY NONCLUSTERED (ID_TRX_TIKET_REFUND)
) WITH (MEMORY_OPTIMIZED=ON);

ALTER TABLE TRX_TIKET_REFUND ADD CONSTRAINT FK_TIKET_REFUND FOREIGN KEY(ID_TRX_TIKET_SALES) REFERENCES TRX_TIKET_SALES(ID_TRX_TIKET_SALES);
ALTER TABLE TRX_TIKET_REFUND ADD CONSTRAINT FK_TIKET_REFUND_STATUS_PESAN FOREIGN KEY(ID_STATUS_PESAN) REFERENCES REF_STATUS_PESAN(ID_STATUS_PESAN);
ALTER TABLE TRX_TIKET_REFUND ADD CONSTRAINT FK_TIKET_REFUND_PENGGUNA FOREIGN KEY(ID_PENGGUNA) REFERENCES ACC_PENGGUNA(ID_PENGGUNA);
ALTER TABLE TRX_TIKET_REFUND ADD CONSTRAINT FK_TIKET_REFUNDJENIS_IDENTITAS FOREIGN KEY(ID_JENIS_IDENTITAS) REFERENCES REF_JENIS_IDENTITAS(ID_JENIS_IDENTITAS);
ALTER TABLE TRX_TIKET_REFUND ADD CONSTRAINT FK_TIKET_STATUS_REFUND FOREIGN KEY(ID_STATUS_REFUND) REFERENCES REF_STATUS_REFUND(ID_STATUS_REFUND);
	
-- CREATE INDEX TRX_TIKET_REFUND_TGL_PENGAJUAN ON TRX_TIKET_REFUND(TGL_PENGAJUAN);
-- CREATE INDEX TRX_TIKET_REFUND_TGL_PROSES ON TRX_TIKET_REFUND(TGL_PROSES);

-- DROP TABLE TRX_TIKET_REFUND_DETAIL;
CREATE TABLE TRX_TIKET_REFUND_DETAIL
(
	[ID_TRX_TIKET_SALES_DETAIL] INT NOT NULL,
	[ID_TRX_TIKET_REFUND] INT,
	[ID_STATUS_REFUND] INT,
	[REFUND] INT DEFAULT 0,
	PRIMARY KEY NONCLUSTERED (ID_TRX_TIKET_SALES_DETAIL)
) WITH (MEMORY_OPTIMIZED=ON);

ALTER TABLE TRX_TIKET_REFUND_DETAIL ADD CONSTRAINT FK_TRX_TIKET_SALES_DETAIL FOREIGN KEY(ID_TRX_TIKET_SALES_DETAIL) REFERENCES TRX_TIKET_SALES_DETAIL(ID_TRX_TIKET_SALES_DETAIL);
ALTER TABLE TRX_TIKET_REFUND_DETAIL ADD CONSTRAINT FK_TRX_TIKET_REFUND FOREIGN KEY(ID_TRX_TIKET_REFUND) REFERENCES TRX_TIKET_REFUND(ID_TRX_TIKET_REFUND);
ALTER TABLE TRX_TIKET_REFUND_DETAIL ADD CONSTRAINT FK_TRX_TIKET_STATUS_REFUND FOREIGN KEY(ID_STATUS_REFUND) REFERENCES REF_STATUS_REFUND(ID_STATUS_REFUND);

